version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}
  phlare_data: {}

services:
  evmos-devnet1:
    image: evmos-devnet1
    container_name: evmos-devnet1
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=tags/v9.1.0
    restart: always
    ports:
      - 8545:8545
      - 26660:26660
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  evmos-devnet2:
    image: evmos-devnet2
    container_name: evmos-devnet2
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=tags/v10.0.0-rc2
        - extra_flags=--metrics
    restart: always
    ports:
      - 26661:26660
      - 8546:8545
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 8090:9090
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 10s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./grafana/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    links:
            - prometheus
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 10s