{
 "title": "Dashboard Evmos 01",
 "description": "just an example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Block Height",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{instance=\"evmos-devnet1:26660\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "tendermint_consensus_latest_block_height{instance=\"evmos-devnet2:26660\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pre-vote Delay",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_full_prevote_message_delay{instance=\"evmos-devnet1:26660\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "tendermint_consensus_full_prevote_message_delay{instance=\"evmos-devnet2:26660\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bucket Block Interval",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(tendermint_consensus_block_interval_seconds_bucket{instance=\"evmos-devnet1:26660\"}[$__rate_interval])))",
     "legendFormat": "evmos-devnet1"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(tendermint_consensus_block_interval_seconds_bucket{instance=\"evmos-devnet2:26660\"}[$__rate_interval])))",
     "legendFormat": "evmos-devnet2"
    }
   ]
  },
  {
   "title": "Pre-vote Delay History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "tendermint_consensus_full_prevote_message_delay{instance=\"evmos-devnet1:26660\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "tendermint_consensus_full_prevote_message_delay{instance=\"evmos-devnet2:26660\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Memstat Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"evmos-devnet1:26660\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"evmos-devnet2:26660\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}